[package]
name = "sandglass"
version = "0.1.1"
authors = ["mib <mib@mib.dev>"]
edition = "2021"

[dependencies]
chrono = "0.4.19"
crossterm = "0.19.0"
ctrlc = "3.1.8"
figlet-rs = "0.1.3"
lazy_static = "1.4.0"
